INSERT INTO songs (author, title, release_date, lyrics, link)
VALUES ('The Beatles', 'Hey Jude', '1968-08-26', 'Hey Jude, don''t make it bad...',
        'https://www.lyrics.com/lyric/2106751/The+Beatles/Hey+Jude'),
       ('Queen', 'Bohemian Rhapsody', '1975-10-31', 'Is this the real life? Is this just fantasy?',
        'https://www.lyrics.com/lyric/29190115/Queen/Bohemian+Rhapsody'),
       ('Adele', 'Rolling in the Deep', '2010-11-29', 'There''s a fire starting in my heart...',
        'https://www.lyrics.com/lyric/21924538/Adele/Rolling+in+the+Deep'),
       ('Elton John', 'Rocket Man', '1972-04-17', 'And I think it''s gonna be a long long time...',
        'https://www.lyrics.com/lyric/28079782/Elton+John/Rocket+Man'),
       ('Nirvana', 'Smells Like Teen Spirit', '1991-09-10', 'Load up on guns, bring your friends...',
        'https://www.lyrics.com/lyric/3568383/Nirvana/Smells+Like+Teen+Spirit'),
       ('Michael Jackson', 'Billie Jean', '1983-01-02', 'Billie Jean is not my lover...',
        'https://www.lyrics.com/lyric/199357/Michael+Jackson/Billie+Jean'),
       ('The Rolling Stones', 'Paint It Black', '1966-05-07', 'I see a red door and I want it painted black...',
        'https://www.lyrics.com/lyric/466008/The+Rolling+Stones/Paint+It+Black'),
       ('The Eagles', 'Hotel California', '1977-02-22', 'Welcome to the Hotel California...',
        'https://www.lyrics.com/lyric/1334046/Eagles/Hotel+California'),
       ('Whitney Houston', 'I Will Always Love You', '1992-11-03', 'And I will always love you...',
        'https://www.lyrics.com/lyric/1648388/Whitney+Houston/I+Will+Always+Love+You'),
       ('Taylor Swift', 'Shake It Off', '2014-08-18', 'Cause the players gonna play, play, play, play, play...',
        'https://www.lyrics.com/lyric/30684741/Taylor+Swift/Shake+It+Off'),
       ('Elvis Presley', 'Can''t Help Falling in Love', '1961-10-01', 'Wise men say, only fools rush in...',
        'https://www.lyrics.com/lyric/112318/Elvis+Presley/Can%27t+Help+Falling+in+Love'),
       ('Ed Sheeran', 'Shape of You', '2017-01-06', 'The club isn''t the best place to find a lover...',
        'https://www.lyrics.com/lyric/33516483/Ed+Sheeran/Shape+of+You'),
       ('John Lennon', 'Imagine', '1971-10-11', 'Imagine there''s no heaven...',
        'https://www.lyrics.com/lyric/3204386/John+Lennon/Imagine'),
       ('Coldplay', 'Yellow', '2000-06-26', 'Look at the stars, look how they shine for you...',
        'https://www.lyrics.com/lyric/3940465/Coldplay/Yellow'),
       ('Madonna', 'Like a Prayer', '1989-03-03', 'Life is a mystery, everyone must stand alone...',
        'https://www.lyrics.com/lyric/265929/Madonna/Like+a+Prayer'),
       ('Beyoncé', 'Halo', '2008-01-20', 'Remember those walls I built? Well, baby, they''re tumbling down...',
        'https://www.lyrics.com/lyric/17124832/Beyonc%C3%A9/Halo'),
       ('Pink Floyd', 'Wish You Were Here', '1975-09-12', 'So, so you think you can tell heaven from hell...',
        'https://www.lyrics.com/lyric/4601723/Pink+Floyd/Wish+You+Were+Here'),
       ('The Police', 'Every Breath You Take', '1983-05-20', 'Every breath you take, every move you make...',
        'https://www.lyrics.com/lyric/185809/The+Police/Every+Breath+You+Take'),
       ('U2', 'With or Without You', '1987-03-06', 'See the stone set in your eyes...',
        'https://www.lyrics.com/lyric/2371102/U2/With+or+Without+You'),
       ('Lady Gaga', 'Bad Romance', '2009-10-26', 'Rah, rah, ah, ah, ah, roma, roma, ma...',
        'https://www.lyrics.com/lyric/18834520/Lady+Gaga/Bad+Romance'),
       ('Rihanna', 'Umbrella', '2007-03-29', 'You can stand under my umbrella...',
        'https://www.lyrics.com/lyric/12245142/Rihanna/Umbrella'),
       ('Ariana Grande', 'Thank U, Next', '2018-11-03', 'Thought I''d end up with Sean, but it wasn''t a match...',
        'https://www.lyrics.com/lyric/35725996/Ariana+Grande/thank+u,+next'),
       ('Drake', 'God''s Plan', '2018-01-19', 'She said do you love me, I tell her only partly...',
        'https://www.lyrics.com/lyric/34820664/Drake/God%27s+Plan'),
       ('Katy Perry', 'Firework', '2010-10-26', 'Cause baby, you''re a firework...',
        'https://www.lyrics.com/lyric/20691543/Katy+Perry/Firework'),
       ('Billie Eilish', 'Bad Guy', '2019-03-29', 'So you''re a tough guy, like it really rough guy...',
        'https://www.lyrics.com/lyric/36249422/Billie+Eilish/bad+guy');